
# Server Configuration
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

# Spring Configuration

spring:

  #to enable colors when you run your app outside intellij
  output:
    ansi:
      enabled: always
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/aftas?createDatabaseIfNotExist=true
    username: aftas
    password: aftas
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: create
jwt:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351


